GET http://localhost:5000/api/user
Authorization: : Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MGU0NmI2ZWZiMTA5MDFhYmMwN2JjYWQiLCJuYW1lIjoia2hhbGlkIiwiZW1haWwiOiJpYnJhaGlta2hhbGlkNDc4QGdtYWlsLmNvbSIsImlhdCI6MTYyNTYzMDA3MSwiZXhwIjoxNjI1NjMzNjcxfQ.HWPC1MYrxUJD-Kk3LDQw6xwUYPwrW9RpUfFC7aQEODA
###

POST http://localhost:5000/api/login
content-type: application/json

{
    "email": "ibrahimkhalid478@gmail.com",
    "password": "khalid"
}
